import React from 'react'
import { Provider } from "react-redux";
import Head from 'next/head'
import '../styles/globals.css'
import store from "store/index";
import type { AppProps } from 'next/app'
import Navbar from 'components/Navbar'

const MyApp = ({ Component, pageProps }: AppProps) => {

  return (
    <Provider store={store}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col justify-center items-center">
        <Navbar />
        <h1>
          Some text for test
        </h1>
        <Component {...pageProps} />
      </main>
    </Provider>

  );
}

export default MyApp