import { useState, useEffect } from 'react'
import { Provider } from "react-redux";
import Head from 'next/head'
import '../styles/globals.css'
import { wrapper } from "store/store";
import type { AppProps } from 'next/app'
import Skeleton from 'components/Skeleton'
import Navbar from 'components/Navbar'

const MyApp = ({ Component, ...rest }: AppProps) => {

  const { store, props } = wrapper.useWrappedStore(rest)
  const { pageProps } = props
  const [isLoading, setIsLoading] = useState(true)

  useEffect(() => {
    setTimeout(() => setIsLoading(false), 1500)
  }, [])

  return (
    <Provider store={store}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col justify-center items-center">
        <Navbar />
        <h1>
          Some text for test
        </h1>
        <div className="flex w-[300px] md:w-[620px] gap-4 flex-wrap">
          {
            isLoading 
            ? <Skeleton />
            : <Component {...pageProps} />
          }
        </div>
      </main>
    </Provider>

  );
}

export default MyApp