import Head from 'next/head'
import axios from 'axios'
import { Inter } from '@next/font/google'
import { IPizza } from 'types'
import Navbar from 'components/Navbar'

const inter = Inter({ subsets: ['latin'] })

interface IProps {
  data: IPizza
}

const Home = ({ data }: IProps | any) => {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <h1>
          Some text for test
        </h1>
        <p>
        </p>
      </main>
    </>
  )
}

export const getServerSideProps = async () => {

  const response = await axios.get(`http://localhost:6767/api/pizzas`)
  return {
    props: {
      data: response.data,
    }
  }
}

export default Home
