import Head from 'next/head'
import { Inter } from '@next/font/google'
import { IPizza } from 'types'
import Navbar from 'components/Navbar'

const inter = Inter({ subsets: ['latin'] })

interface IProps {
  data: IPizza
}

const Home = ({ data }: IProps) => {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <h1>
          Some text for test
        </h1>
        <p>
          {data.name}
        </p>
      </main>
    </>
  )
}

export const getServerSideProps = async () => {

  const res = await fetch(`http://localhost:6769/api/pizzas/1`)
  const data = await res.json()

  return {
    props: {
      data
    }
  }
}

export default Home
